<?php

class model_showcart3 extends Model
{
    function __construct()
    {
        parent::__construct();
    }
    function getBasketReview()
    {
        return parent::getBasket(); // TODO: Change the autogenerated stub
    }

    function postPrice(){
        self::sessionInit();
        $addressInfo = self::sessionGet('addressInfo');
        $addressInfo = unserialize($addressInfo);

        $posttypeId=self::sessionGet('posttypeId');

        $cityId = $addressInfo['city'];
        $postPrice = $this->calculatePostPrice($cityId);

        if($posttypeId==1){
            $postPrice = $postPrice['pishtaz'];
        }
        elseif ($posttypeId==2){
            $postPrice = $postPrice['sefareshi'];
        }
        return $postPrice;
    }
}

?>